### ISSUE TITLE
Add a number of results?

### ISSUE THREAD

**Issue by stevieflow** [iati-data-access/iati-data-access.github.io#40]
From a filter page such as 

https://countrydata.iatistandard.org/data/custom/?drilldowns=sector%3Bactivity.iati_identifier&filters=recipient_country_or_region%3ACA%3Breporting_organisation%3ACA-3%3Btransaction_type%3A3,4,budget%3Byear%3A2022

We default to 10 results - but there is no indication of the number of results in this search

It could be argued that this page serves as a download preview, so the results will follow (in the download) - but if it is feasible to include the number of results onscreen, it could be a useful addition

**Comment by markbrough** [comment]
This is now fixed! Thanks for the suggestion and sorry it took a while!

**Comment by markbrough** [comment]
This is what that page looks like now:
<img width="1046" alt="image" src="https://github.com/iati-data-access/iati-data-access.github.io/assets/688113/877cfdb9-f1ad-45a2-8021-950242754f31">
